# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 06:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('idcarrito', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'carrito',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Consola',
            fields=[
                ('idconsola', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'consola',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('idgenero', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45, unique=True)),
            ],
            options={
                'db_table': 'genero',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('iditem', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45, unique=True)),
                ('descripcion', models.TextField()),
                ('precio', models.FloatField()),
                ('fecha_salida', models.DateField()),
                ('imagen', models.ImageField(default='imagenes/noimage.png', upload_to='imagenes/')),
                ('consolas_item', models.ManyToManyField(to='shop.Consola')),
                ('generos_item', models.ManyToManyField(to='shop.Genero')),
            ],
            options={
                'db_table': 'item',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('idtipo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'tipo',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('idusuario', models.AutoField(primary_key=True, serialize=False)),
                ('usuario', models.CharField(max_length=15, unique=True)),
                ('nombre', models.CharField(max_length=45)),
                ('apellido', models.CharField(max_length=45)),
                ('correo', models.CharField(max_length=45)),
                ('password', models.CharField(max_length=45)),
                ('dinero', models.FloatField(default=10000)),
                ('carrito_idcarrito', models.ForeignKey(db_column='carrito_idcarrito', on_delete=django.db.models.deletion.DO_NOTHING, to='shop.Carrito')),
                ('tipo_idtipo', models.ForeignKey(db_column='tipo_idtipo', on_delete=django.db.models.deletion.DO_NOTHING, to='shop.Tipo')),
            ],
            options={
                'db_table': 'usuario',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='carrito',
            name='items_carrito',
            field=models.ManyToManyField(to='shop.Item'),
        ),
    ]
