# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 07:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrito',
            name='items_carrito',
            field=models.ManyToManyField(blank=True, to='shop.Item'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='carrito_idcarrito',
            field=models.ForeignKey(blank=True, db_column='carrito_idcarrito', on_delete=django.db.models.deletion.DO_NOTHING, to='shop.Carrito'),
        ),
    ]
