# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 22:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20170725_0407'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='items',
            field=models.ManyToManyField(to='shop.Item'),
        ),
    ]
