# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 15:41
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_usuario_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='precio',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='dinero',
            field=models.FloatField(default=10000, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='items',
            field=models.ManyToManyField(blank=True, to='shop.Item'),
        ),
    ]
